name: RepLedger
options:
  bundleIdPrefix: com.repledger
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.9"
  ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  RepLedger:
    type: application
    platform: iOS
    sources:
      - path: RepLedger
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.repledger.app
        PRODUCT_NAME: RepLedger
        INFOPLIST_FILE: RepLedger/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        SUPPORTS_MACCATALYST: true
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: false
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
        TARGETED_DEVICE_FAMILY: "1,2,6"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          DEVELOPMENT_TEAM: ""
        Release:
          CODE_SIGN_IDENTITY: "-"
          DEVELOPMENT_TEAM: ""
    entitlements:
      path: RepLedger/RepLedger.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
    info:
      path: RepLedger/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
        ITSAppUsesNonExemptEncryption: false

schemes:
  RepLedger:
    build:
      targets:
        RepLedger: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
